//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SVMSalesModel", "FK_PricingOverrides_Products", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SalesWSServices.Data.Product), "PricingRecords", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SalesWSServices.Data.PricingRecord), true)]

#endregion

namespace SalesWSServices.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SVMSalesWSDB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SVMSalesWSDB object using the connection string found in the 'SVMSalesWSDB' section of the application configuration file.
        /// </summary>
        public SVMSalesWSDB() : base("name=SVMSalesWSDB", "SVMSalesWSDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SVMSalesWSDB object.
        /// </summary>
        public SVMSalesWSDB(string connectionString) : base(connectionString, "SVMSalesWSDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SVMSalesWSDB object.
        /// </summary>
        public SVMSalesWSDB(EntityConnection connection) : base(connection, "SVMSalesWSDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Branch_Product> Branch_Product
        {
            get
            {
                if ((_Branch_Product == null))
                {
                    _Branch_Product = base.CreateObjectSet<Branch_Product>("Branch_Product");
                }
                return _Branch_Product;
            }
        }
        private ObjectSet<Branch_Product> _Branch_Product;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PricingRecord> PricingRecords
        {
            get
            {
                if ((_PricingRecords == null))
                {
                    _PricingRecords = base.CreateObjectSet<PricingRecord>("PricingRecords");
                }
                return _PricingRecords;
            }
        }
        private ObjectSet<PricingRecord> _PricingRecords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Region_Product> Region_Product
        {
            get
            {
                if ((_Region_Product == null))
                {
                    _Region_Product = base.CreateObjectSet<Region_Product>("Region_Product");
                }
                return _Region_Product;
            }
        }
        private ObjectSet<Region_Product> _Region_Product;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Branch_Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBranch_Product(Branch_Product branch_Product)
        {
            base.AddObject("Branch_Product", branch_Product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PricingRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPricingRecords(PricingRecord pricingRecord)
        {
            base.AddObject("PricingRecords", pricingRecord);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Region_Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegion_Product(Region_Product region_Product)
        {
            base.AddObject("Region_Product", region_Product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SVMSalesModel", Name="Branch_Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Branch_Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Branch_Product object.
        /// </summary>
        /// <param name="branchID">Initial value of the BranchID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static Branch_Product CreateBranch_Product(global::System.String branchID, global::System.Int32 productID)
        {
            Branch_Product branch_Product = new Branch_Product();
            branch_Product.BranchID = branchID;
            branch_Product.ProductID = productID;
            return branch_Product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BranchID
        {
            get
            {
                return _BranchID;
            }
            set
            {
                if (_BranchID != value)
                {
                    OnBranchIDChanging(value);
                    ReportPropertyChanging("BranchID");
                    _BranchID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BranchID");
                    OnBranchIDChanged();
                }
            }
        }
        private global::System.String _BranchID;
        partial void OnBranchIDChanging(global::System.String value);
        partial void OnBranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CartState
        {
            get
            {
                return _CartState;
            }
            set
            {
                OnCartStateChanging(value);
                ReportPropertyChanging("CartState");
                _CartState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CartState");
                OnCartStateChanged();
            }
        }
        private global::System.String _CartState;
        partial void OnCartStateChanging(global::System.String value);
        partial void OnCartStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateActiveFrom
        {
            get
            {
                return _DateActiveFrom;
            }
            set
            {
                OnDateActiveFromChanging(value);
                ReportPropertyChanging("DateActiveFrom");
                _DateActiveFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateActiveFrom");
                OnDateActiveFromChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateActiveFrom;
        partial void OnDateActiveFromChanging(Nullable<global::System.DateTime> value);
        partial void OnDateActiveFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateActiveTo
        {
            get
            {
                return _DateActiveTo;
            }
            set
            {
                OnDateActiveToChanging(value);
                ReportPropertyChanging("DateActiveTo");
                _DateActiveTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateActiveTo");
                OnDateActiveToChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateActiveTo;
        partial void OnDateActiveToChanging(Nullable<global::System.DateTime> value);
        partial void OnDateActiveToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumVisits
        {
            get
            {
                return _NumVisits;
            }
            set
            {
                OnNumVisitsChanging(value);
                ReportPropertyChanging("NumVisits");
                _NumVisits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumVisits");
                OnNumVisitsChanged();
            }
        }
        private Nullable<global::System.Int32> _NumVisits;
        partial void OnNumVisitsChanging(Nullable<global::System.Int32> value);
        partial void OnNumVisitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BranchBrand
        {
            get
            {
                return _BranchBrand;
            }
            set
            {
                OnBranchBrandChanging(value);
                ReportPropertyChanging("BranchBrand");
                _BranchBrand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BranchBrand");
                OnBranchBrandChanged();
            }
        }
        private global::System.String _BranchBrand;
        partial void OnBranchBrandChanging(global::System.String value);
        partial void OnBranchBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MissionTemplateCode
        {
            get
            {
                return _MissionTemplateCode;
            }
            set
            {
                OnMissionTemplateCodeChanging(value);
                ReportPropertyChanging("MissionTemplateCode");
                _MissionTemplateCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MissionTemplateCode");
                OnMissionTemplateCodeChanged();
            }
        }
        private global::System.String _MissionTemplateCode;
        partial void OnMissionTemplateCodeChanging(global::System.String value);
        partial void OnMissionTemplateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceStart
        {
            get
            {
                return _ServiceStart;
            }
            set
            {
                OnServiceStartChanging(value);
                ReportPropertyChanging("ServiceStart");
                _ServiceStart = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceStart");
                OnServiceStartChanged();
            }
        }
        private global::System.String _ServiceStart;
        partial void OnServiceStartChanging(global::System.String value);
        partial void OnServiceStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceEnd
        {
            get
            {
                return _ServiceEnd;
            }
            set
            {
                OnServiceEndChanging(value);
                ReportPropertyChanging("ServiceEnd");
                _ServiceEnd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceEnd");
                OnServiceEndChanged();
            }
        }
        private global::System.String _ServiceEnd;
        partial void OnServiceEndChanging(global::System.String value);
        partial void OnServiceEndChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SVMSalesModel", Name="PricingRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PricingRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PricingRecord object.
        /// </summary>
        /// <param name="pricingRecordID">Initial value of the PricingRecordID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="iNI_Amount">Initial value of the INI_Amount property.</param>
        /// <param name="reg_Amount">Initial value of the Reg_Amount property.</param>
        /// <param name="renewal_Amount">Initial value of the Renewal_Amount property.</param>
        /// <param name="oneTime_Amount">Initial value of the OneTime_Amount property.</param>
        /// <param name="sqFtFrom">Initial value of the SqFtFrom property.</param>
        /// <param name="sqFtTo">Initial value of the SqFtTo property.</param>
        /// <param name="isMultiplier">Initial value of the IsMultiplier property.</param>
        /// <param name="isBaseRecord">Initial value of the IsBaseRecord property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="lastUpdatedBy">Initial value of the LastUpdatedBy property.</param>
        /// <param name="dateLastUpdated">Initial value of the DateLastUpdated property.</param>
        public static PricingRecord CreatePricingRecord(global::System.Int32 pricingRecordID, global::System.Int32 productID, global::System.Decimal iNI_Amount, global::System.Decimal reg_Amount, global::System.Decimal renewal_Amount, global::System.Decimal oneTime_Amount, global::System.Int32 sqFtFrom, global::System.Int32 sqFtTo, global::System.Boolean isMultiplier, global::System.Boolean isBaseRecord, global::System.String createdBy, global::System.DateTime dateCreated, global::System.String lastUpdatedBy, global::System.DateTime dateLastUpdated)
        {
            PricingRecord pricingRecord = new PricingRecord();
            pricingRecord.PricingRecordID = pricingRecordID;
            pricingRecord.ProductID = productID;
            pricingRecord.INI_Amount = iNI_Amount;
            pricingRecord.Reg_Amount = reg_Amount;
            pricingRecord.Renewal_Amount = renewal_Amount;
            pricingRecord.OneTime_Amount = oneTime_Amount;
            pricingRecord.SqFtFrom = sqFtFrom;
            pricingRecord.SqFtTo = sqFtTo;
            pricingRecord.IsMultiplier = isMultiplier;
            pricingRecord.IsBaseRecord = isBaseRecord;
            pricingRecord.CreatedBy = createdBy;
            pricingRecord.DateCreated = dateCreated;
            pricingRecord.LastUpdatedBy = lastUpdatedBy;
            pricingRecord.DateLastUpdated = dateLastUpdated;
            return pricingRecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PricingRecordID
        {
            get
            {
                return _PricingRecordID;
            }
            set
            {
                if (_PricingRecordID != value)
                {
                    OnPricingRecordIDChanging(value);
                    ReportPropertyChanging("PricingRecordID");
                    _PricingRecordID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PricingRecordID");
                    OnPricingRecordIDChanged();
                }
            }
        }
        private global::System.Int32 _PricingRecordID;
        partial void OnPricingRecordIDChanging(global::System.Int32 value);
        partial void OnPricingRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.String _Division;
        partial void OnDivisionChanging(global::System.String value);
        partial void OnDivisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Branch
        {
            get
            {
                return _Branch;
            }
            set
            {
                OnBranchChanging(value);
                ReportPropertyChanging("Branch");
                _Branch = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Branch");
                OnBranchChanged();
            }
        }
        private global::System.String _Branch;
        partial void OnBranchChanging(global::System.String value);
        partial void OnBranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal INI_Amount
        {
            get
            {
                return _INI_Amount;
            }
            set
            {
                OnINI_AmountChanging(value);
                ReportPropertyChanging("INI_Amount");
                _INI_Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INI_Amount");
                OnINI_AmountChanged();
            }
        }
        private global::System.Decimal _INI_Amount;
        partial void OnINI_AmountChanging(global::System.Decimal value);
        partial void OnINI_AmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Reg_Amount
        {
            get
            {
                return _Reg_Amount;
            }
            set
            {
                OnReg_AmountChanging(value);
                ReportPropertyChanging("Reg_Amount");
                _Reg_Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reg_Amount");
                OnReg_AmountChanged();
            }
        }
        private global::System.Decimal _Reg_Amount;
        partial void OnReg_AmountChanging(global::System.Decimal value);
        partial void OnReg_AmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Renewal_Amount
        {
            get
            {
                return _Renewal_Amount;
            }
            set
            {
                OnRenewal_AmountChanging(value);
                ReportPropertyChanging("Renewal_Amount");
                _Renewal_Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Renewal_Amount");
                OnRenewal_AmountChanged();
            }
        }
        private global::System.Decimal _Renewal_Amount;
        partial void OnRenewal_AmountChanging(global::System.Decimal value);
        partial void OnRenewal_AmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal OneTime_Amount
        {
            get
            {
                return _OneTime_Amount;
            }
            set
            {
                OnOneTime_AmountChanging(value);
                ReportPropertyChanging("OneTime_Amount");
                _OneTime_Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OneTime_Amount");
                OnOneTime_AmountChanged();
            }
        }
        private global::System.Decimal _OneTime_Amount;
        partial void OnOneTime_AmountChanging(global::System.Decimal value);
        partial void OnOneTime_AmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SqFtFrom
        {
            get
            {
                return _SqFtFrom;
            }
            set
            {
                OnSqFtFromChanging(value);
                ReportPropertyChanging("SqFtFrom");
                _SqFtFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SqFtFrom");
                OnSqFtFromChanged();
            }
        }
        private global::System.Int32 _SqFtFrom;
        partial void OnSqFtFromChanging(global::System.Int32 value);
        partial void OnSqFtFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SqFtTo
        {
            get
            {
                return _SqFtTo;
            }
            set
            {
                OnSqFtToChanging(value);
                ReportPropertyChanging("SqFtTo");
                _SqFtTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SqFtTo");
                OnSqFtToChanged();
            }
        }
        private global::System.Int32 _SqFtTo;
        partial void OnSqFtToChanging(global::System.Int32 value);
        partial void OnSqFtToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMultiplier
        {
            get
            {
                return _IsMultiplier;
            }
            set
            {
                OnIsMultiplierChanging(value);
                ReportPropertyChanging("IsMultiplier");
                _IsMultiplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMultiplier");
                OnIsMultiplierChanged();
            }
        }
        private global::System.Boolean _IsMultiplier;
        partial void OnIsMultiplierChanging(global::System.Boolean value);
        partial void OnIsMultiplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsBaseRecord
        {
            get
            {
                return _IsBaseRecord;
            }
            set
            {
                OnIsBaseRecordChanging(value);
                ReportPropertyChanging("IsBaseRecord");
                _IsBaseRecord = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBaseRecord");
                OnIsBaseRecordChanged();
            }
        }
        private global::System.Boolean _IsBaseRecord;
        partial void OnIsBaseRecordChanging(global::System.Boolean value);
        partial void OnIsBaseRecordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateLastUpdated
        {
            get
            {
                return _DateLastUpdated;
            }
            set
            {
                OnDateLastUpdatedChanging(value);
                ReportPropertyChanging("DateLastUpdated");
                _DateLastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLastUpdated");
                OnDateLastUpdatedChanged();
            }
        }
        private global::System.DateTime _DateLastUpdated;
        partial void OnDateLastUpdatedChanging(global::System.DateTime value);
        partial void OnDateLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FlatCostPerSqFt
        {
            get
            {
                return _FlatCostPerSqFt;
            }
            set
            {
                OnFlatCostPerSqFtChanging(value);
                ReportPropertyChanging("FlatCostPerSqFt");
                _FlatCostPerSqFt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlatCostPerSqFt");
                OnFlatCostPerSqFtChanged();
            }
        }
        private Nullable<global::System.Int32> _FlatCostPerSqFt;
        partial void OnFlatCostPerSqFtChanging(Nullable<global::System.Int32> value);
        partial void OnFlatCostPerSqFtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FlatCostPerSqFtPrice
        {
            get
            {
                return _FlatCostPerSqFtPrice;
            }
            set
            {
                OnFlatCostPerSqFtPriceChanging(value);
                ReportPropertyChanging("FlatCostPerSqFtPrice");
                _FlatCostPerSqFtPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FlatCostPerSqFtPrice");
                OnFlatCostPerSqFtPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _FlatCostPerSqFtPrice;
        partial void OnFlatCostPerSqFtPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnFlatCostPerSqFtPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SpcFlatCostPerSqFt
        {
            get
            {
                return _SpcFlatCostPerSqFt;
            }
            set
            {
                OnSpcFlatCostPerSqFtChanging(value);
                ReportPropertyChanging("SpcFlatCostPerSqFt");
                _SpcFlatCostPerSqFt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpcFlatCostPerSqFt");
                OnSpcFlatCostPerSqFtChanged();
            }
        }
        private Nullable<global::System.Int32> _SpcFlatCostPerSqFt;
        partial void OnSpcFlatCostPerSqFtChanging(Nullable<global::System.Int32> value);
        partial void OnSpcFlatCostPerSqFtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SpcFlatCostPerSqFtPrice
        {
            get
            {
                return _SpcFlatCostPerSqFtPrice;
            }
            set
            {
                OnSpcFlatCostPerSqFtPriceChanging(value);
                ReportPropertyChanging("SpcFlatCostPerSqFtPrice");
                _SpcFlatCostPerSqFtPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpcFlatCostPerSqFtPrice");
                OnSpcFlatCostPerSqFtPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _SpcFlatCostPerSqFtPrice;
        partial void OnSpcFlatCostPerSqFtPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnSpcFlatCostPerSqFtPriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SVMSalesModel", "FK_PricingOverrides_Products", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SVMSalesModel.FK_PricingOverrides_Products", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SVMSalesModel.FK_PricingOverrides_Products", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("SVMSalesModel.FK_PricingOverrides_Products", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("SVMSalesModel.FK_PricingOverrides_Products", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SVMSalesModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="busUnit">Initial value of the BusUnit property.</param>
        /// <param name="cartState">Initial value of the CartState property.</param>
        /// <param name="allowGeneralDiscount">Initial value of the AllowGeneralDiscount property.</param>
        /// <param name="outputType">Initial value of the OutputType property.</param>
        /// <param name="scheduling">Initial value of the Scheduling property.</param>
        /// <param name="commissionPct">Initial value of the CommissionPct property.</param>
        /// <param name="allowPrepayDiscount">Initial value of the AllowPrepayDiscount property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="lastUpdatedBy">Initial value of the LastUpdatedBy property.</param>
        /// <param name="dateLastUpdated">Initial value of the DateLastUpdated property.</param>
        /// <param name="availableForCrossSell">Initial value of the AvailableForCrossSell property.</param>
        /// <param name="treeShrubService">Initial value of the TreeShrubService property.</param>
        /// <param name="requiresEasyPay">Initial value of the RequiresEasyPay property.</param>
        /// <param name="itemTaxOverride">Initial value of the ItemTaxOverride property.</param>
        /// <param name="isPlanFlag">Initial value of the IsPlanFlag property.</param>
        /// <param name="isOneTime">Initial value of the IsOneTime property.</param>
        /// <param name="includeOneTimeAmount">Initial value of the IncludeOneTimeAmount property.</param>
        public static Product CreateProduct(global::System.Int32 productID, global::System.String name, global::System.String busUnit, global::System.String cartState, global::System.Boolean allowGeneralDiscount, global::System.String outputType, global::System.String scheduling, global::System.Decimal commissionPct, global::System.Boolean allowPrepayDiscount, global::System.String createdBy, global::System.DateTime dateCreated, global::System.String lastUpdatedBy, global::System.DateTime dateLastUpdated, global::System.Boolean availableForCrossSell, global::System.Boolean treeShrubService, global::System.Boolean requiresEasyPay, global::System.Boolean itemTaxOverride, global::System.Boolean isPlanFlag, global::System.Boolean isOneTime, global::System.Boolean includeOneTimeAmount)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.Name = name;
            product.BusUnit = busUnit;
            product.CartState = cartState;
            product.AllowGeneralDiscount = allowGeneralDiscount;
            product.OutputType = outputType;
            product.Scheduling = scheduling;
            product.CommissionPct = commissionPct;
            product.AllowPrepayDiscount = allowPrepayDiscount;
            product.CreatedBy = createdBy;
            product.DateCreated = dateCreated;
            product.LastUpdatedBy = lastUpdatedBy;
            product.DateLastUpdated = dateLastUpdated;
            product.AvailableForCrossSell = availableForCrossSell;
            product.TreeShrubService = treeShrubService;
            product.RequiresEasyPay = requiresEasyPay;
            product.ItemTaxOverride = itemTaxOverride;
            product.IsPlanFlag = isPlanFlag;
            product.IsOneTime = isOneTime;
            product.IncludeOneTimeAmount = includeOneTimeAmount;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MissionTemplateCode
        {
            get
            {
                return _MissionTemplateCode;
            }
            set
            {
                OnMissionTemplateCodeChanging(value);
                ReportPropertyChanging("MissionTemplateCode");
                _MissionTemplateCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MissionTemplateCode");
                OnMissionTemplateCodeChanged();
            }
        }
        private global::System.String _MissionTemplateCode;
        partial void OnMissionTemplateCodeChanging(global::System.String value);
        partial void OnMissionTemplateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BusUnit
        {
            get
            {
                return _BusUnit;
            }
            set
            {
                OnBusUnitChanging(value);
                ReportPropertyChanging("BusUnit");
                _BusUnit = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BusUnit");
                OnBusUnitChanged();
            }
        }
        private global::System.String _BusUnit;
        partial void OnBusUnitChanging(global::System.String value);
        partial void OnBusUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CartState
        {
            get
            {
                return _CartState;
            }
            set
            {
                OnCartStateChanging(value);
                ReportPropertyChanging("CartState");
                _CartState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CartState");
                OnCartStateChanged();
            }
        }
        private global::System.String _CartState;
        partial void OnCartStateChanging(global::System.String value);
        partial void OnCartStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllowGeneralDiscount
        {
            get
            {
                return _AllowGeneralDiscount;
            }
            set
            {
                OnAllowGeneralDiscountChanging(value);
                ReportPropertyChanging("AllowGeneralDiscount");
                _AllowGeneralDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowGeneralDiscount");
                OnAllowGeneralDiscountChanged();
            }
        }
        private global::System.Boolean _AllowGeneralDiscount;
        partial void OnAllowGeneralDiscountChanging(global::System.Boolean value);
        partial void OnAllowGeneralDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OutputType
        {
            get
            {
                return _OutputType;
            }
            set
            {
                OnOutputTypeChanging(value);
                ReportPropertyChanging("OutputType");
                _OutputType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OutputType");
                OnOutputTypeChanged();
            }
        }
        private global::System.String _OutputType;
        partial void OnOutputTypeChanging(global::System.String value);
        partial void OnOutputTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Scheduling
        {
            get
            {
                return _Scheduling;
            }
            set
            {
                OnSchedulingChanging(value);
                ReportPropertyChanging("Scheduling");
                _Scheduling = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Scheduling");
                OnSchedulingChanged();
            }
        }
        private global::System.String _Scheduling;
        partial void OnSchedulingChanging(global::System.String value);
        partial void OnSchedulingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchedulingType
        {
            get
            {
                return _SchedulingType;
            }
            set
            {
                OnSchedulingTypeChanging(value);
                ReportPropertyChanging("SchedulingType");
                _SchedulingType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchedulingType");
                OnSchedulingTypeChanged();
            }
        }
        private global::System.String _SchedulingType;
        partial void OnSchedulingTypeChanging(global::System.String value);
        partial void OnSchedulingTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CommissionPct
        {
            get
            {
                return _CommissionPct;
            }
            set
            {
                OnCommissionPctChanging(value);
                ReportPropertyChanging("CommissionPct");
                _CommissionPct = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommissionPct");
                OnCommissionPctChanged();
            }
        }
        private global::System.Decimal _CommissionPct;
        partial void OnCommissionPctChanging(global::System.Decimal value);
        partial void OnCommissionPctChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllowPrepayDiscount
        {
            get
            {
                return _AllowPrepayDiscount;
            }
            set
            {
                OnAllowPrepayDiscountChanging(value);
                ReportPropertyChanging("AllowPrepayDiscount");
                _AllowPrepayDiscount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowPrepayDiscount");
                OnAllowPrepayDiscountChanged();
            }
        }
        private global::System.Boolean _AllowPrepayDiscount;
        partial void OnAllowPrepayDiscountChanging(global::System.Boolean value);
        partial void OnAllowPrepayDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedBy
        {
            get
            {
                return _LastUpdatedBy;
            }
            set
            {
                OnLastUpdatedByChanging(value);
                ReportPropertyChanging("LastUpdatedBy");
                _LastUpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastUpdatedBy");
                OnLastUpdatedByChanged();
            }
        }
        private global::System.String _LastUpdatedBy;
        partial void OnLastUpdatedByChanging(global::System.String value);
        partial void OnLastUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateLastUpdated
        {
            get
            {
                return _DateLastUpdated;
            }
            set
            {
                OnDateLastUpdatedChanging(value);
                ReportPropertyChanging("DateLastUpdated");
                _DateLastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLastUpdated");
                OnDateLastUpdatedChanged();
            }
        }
        private global::System.DateTime _DateLastUpdated;
        partial void OnDateLastUpdatedChanging(global::System.DateTime value);
        partial void OnDateLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceLine
        {
            get
            {
                return _ServiceLine;
            }
            set
            {
                OnServiceLineChanging(value);
                ReportPropertyChanging("ServiceLine");
                _ServiceLine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceLine");
                OnServiceLineChanged();
            }
        }
        private global::System.String _ServiceLine;
        partial void OnServiceLineChanging(global::System.String value);
        partial void OnServiceLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _SortOrder;
        partial void OnSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AvailableForCrossSell
        {
            get
            {
                return _AvailableForCrossSell;
            }
            set
            {
                OnAvailableForCrossSellChanging(value);
                ReportPropertyChanging("AvailableForCrossSell");
                _AvailableForCrossSell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvailableForCrossSell");
                OnAvailableForCrossSellChanged();
            }
        }
        private global::System.Boolean _AvailableForCrossSell;
        partial void OnAvailableForCrossSellChanging(global::System.Boolean value);
        partial void OnAvailableForCrossSellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TreeShrubService
        {
            get
            {
                return _TreeShrubService;
            }
            set
            {
                OnTreeShrubServiceChanging(value);
                ReportPropertyChanging("TreeShrubService");
                _TreeShrubService = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TreeShrubService");
                OnTreeShrubServiceChanged();
            }
        }
        private global::System.Boolean _TreeShrubService;
        partial void OnTreeShrubServiceChanging(global::System.Boolean value);
        partial void OnTreeShrubServiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean RequiresEasyPay
        {
            get
            {
                return _RequiresEasyPay;
            }
            set
            {
                OnRequiresEasyPayChanging(value);
                ReportPropertyChanging("RequiresEasyPay");
                _RequiresEasyPay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequiresEasyPay");
                OnRequiresEasyPayChanged();
            }
        }
        private global::System.Boolean _RequiresEasyPay;
        partial void OnRequiresEasyPayChanging(global::System.Boolean value);
        partial void OnRequiresEasyPayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ItemTaxOverride
        {
            get
            {
                return _ItemTaxOverride;
            }
            set
            {
                OnItemTaxOverrideChanging(value);
                ReportPropertyChanging("ItemTaxOverride");
                _ItemTaxOverride = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemTaxOverride");
                OnItemTaxOverrideChanged();
            }
        }
        private global::System.Boolean _ItemTaxOverride;
        partial void OnItemTaxOverrideChanging(global::System.Boolean value);
        partial void OnItemTaxOverrideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPlanFlag
        {
            get
            {
                return _IsPlanFlag;
            }
            set
            {
                OnIsPlanFlagChanging(value);
                ReportPropertyChanging("IsPlanFlag");
                _IsPlanFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPlanFlag");
                OnIsPlanFlagChanged();
            }
        }
        private global::System.Boolean _IsPlanFlag;
        partial void OnIsPlanFlagChanging(global::System.Boolean value);
        partial void OnIsPlanFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsOneTime
        {
            get
            {
                return _IsOneTime;
            }
            set
            {
                OnIsOneTimeChanging(value);
                ReportPropertyChanging("IsOneTime");
                _IsOneTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsOneTime");
                OnIsOneTimeChanged();
            }
        }
        private global::System.Boolean _IsOneTime;
        partial void OnIsOneTimeChanging(global::System.Boolean value);
        partial void OnIsOneTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IncludeOneTimeAmount
        {
            get
            {
                return _IncludeOneTimeAmount;
            }
            set
            {
                OnIncludeOneTimeAmountChanging(value);
                ReportPropertyChanging("IncludeOneTimeAmount");
                _IncludeOneTimeAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncludeOneTimeAmount");
                OnIncludeOneTimeAmountChanged();
            }
        }
        private global::System.Boolean _IncludeOneTimeAmount;
        partial void OnIncludeOneTimeAmountChanging(global::System.Boolean value);
        partial void OnIncludeOneTimeAmountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SVMSalesModel", "FK_PricingOverrides_Products", "PricingRecords")]
        public EntityCollection<PricingRecord> PricingRecords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PricingRecord>("SVMSalesModel.FK_PricingOverrides_Products", "PricingRecords");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PricingRecord>("SVMSalesModel.FK_PricingOverrides_Products", "PricingRecords", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SVMSalesModel", Name="Region_Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Region_Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Region_Product object.
        /// </summary>
        /// <param name="regionID">Initial value of the RegionID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="numVisits">Initial value of the NumVisits property.</param>
        public static Region_Product CreateRegion_Product(global::System.String regionID, global::System.Int32 productID, global::System.Int32 numVisits)
        {
            Region_Product region_Product = new Region_Product();
            region_Product.RegionID = regionID;
            region_Product.ProductID = productID;
            region_Product.NumVisits = numVisits;
            return region_Product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                if (_RegionID != value)
                {
                    OnRegionIDChanging(value);
                    ReportPropertyChanging("RegionID");
                    _RegionID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RegionID");
                    OnRegionIDChanged();
                }
            }
        }
        private global::System.String _RegionID;
        partial void OnRegionIDChanging(global::System.String value);
        partial void OnRegionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CartState
        {
            get
            {
                return _CartState;
            }
            set
            {
                OnCartStateChanging(value);
                ReportPropertyChanging("CartState");
                _CartState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CartState");
                OnCartStateChanged();
            }
        }
        private global::System.String _CartState;
        partial void OnCartStateChanging(global::System.String value);
        partial void OnCartStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateActiveFrom
        {
            get
            {
                return _DateActiveFrom;
            }
            set
            {
                OnDateActiveFromChanging(value);
                ReportPropertyChanging("DateActiveFrom");
                _DateActiveFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateActiveFrom");
                OnDateActiveFromChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateActiveFrom;
        partial void OnDateActiveFromChanging(Nullable<global::System.DateTime> value);
        partial void OnDateActiveFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateActiveTo
        {
            get
            {
                return _DateActiveTo;
            }
            set
            {
                OnDateActiveToChanging(value);
                ReportPropertyChanging("DateActiveTo");
                _DateActiveTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateActiveTo");
                OnDateActiveToChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateActiveTo;
        partial void OnDateActiveToChanging(Nullable<global::System.DateTime> value);
        partial void OnDateActiveToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumVisits
        {
            get
            {
                return _NumVisits;
            }
            set
            {
                OnNumVisitsChanging(value);
                ReportPropertyChanging("NumVisits");
                _NumVisits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumVisits");
                OnNumVisitsChanged();
            }
        }
        private global::System.Int32 _NumVisits;
        partial void OnNumVisitsChanging(global::System.Int32 value);
        partial void OnNumVisitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionBrand
        {
            get
            {
                return _RegionBrand;
            }
            set
            {
                OnRegionBrandChanging(value);
                ReportPropertyChanging("RegionBrand");
                _RegionBrand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegionBrand");
                OnRegionBrandChanged();
            }
        }
        private global::System.String _RegionBrand;
        partial void OnRegionBrandChanging(global::System.String value);
        partial void OnRegionBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceStart
        {
            get
            {
                return _ServiceStart;
            }
            set
            {
                OnServiceStartChanging(value);
                ReportPropertyChanging("ServiceStart");
                _ServiceStart = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceStart");
                OnServiceStartChanged();
            }
        }
        private global::System.String _ServiceStart;
        partial void OnServiceStartChanging(global::System.String value);
        partial void OnServiceStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceEnd
        {
            get
            {
                return _ServiceEnd;
            }
            set
            {
                OnServiceEndChanging(value);
                ReportPropertyChanging("ServiceEnd");
                _ServiceEnd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceEnd");
                OnServiceEndChanged();
            }
        }
        private global::System.String _ServiceEnd;
        partial void OnServiceEndChanging(global::System.String value);
        partial void OnServiceEndChanged();

        #endregion
    
    }

    #endregion
    
}
