//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWSTool.ServiceSalesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsProducts", Namespace="http://schemas.datacontract.org/2004/07/SalesWSServices.Services")]
    [System.SerializableAttribute()]
    public partial class wsProducts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PricingRecord", Namespace="http://schemas.datacontract.org/2004/07/SalesWSServices.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PricingRecord : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FlatCostPerSqFtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FlatCostPerSqFtPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal INI_AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBaseRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMultiplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OneTime_AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PricingRecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SalesWSTool.ServiceSalesWS.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<SalesWSTool.ServiceSalesWS.Product> ProductReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Reg_AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Renewal_AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SpcFlatCostPerSqFtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SpcFlatCostPerSqFtPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SqFtFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SqFtToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastUpdated {
            get {
                return this.DateLastUpdatedField;
            }
            set {
                if ((this.DateLastUpdatedField.Equals(value) != true)) {
                    this.DateLastUpdatedField = value;
                    this.RaisePropertyChanged("DateLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division {
            get {
                return this.DivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionField, value) != true)) {
                    this.DivisionField = value;
                    this.RaisePropertyChanged("Division");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FlatCostPerSqFt {
            get {
                return this.FlatCostPerSqFtField;
            }
            set {
                if ((this.FlatCostPerSqFtField.Equals(value) != true)) {
                    this.FlatCostPerSqFtField = value;
                    this.RaisePropertyChanged("FlatCostPerSqFt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FlatCostPerSqFtPrice {
            get {
                return this.FlatCostPerSqFtPriceField;
            }
            set {
                if ((this.FlatCostPerSqFtPriceField.Equals(value) != true)) {
                    this.FlatCostPerSqFtPriceField = value;
                    this.RaisePropertyChanged("FlatCostPerSqFtPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal INI_Amount {
            get {
                return this.INI_AmountField;
            }
            set {
                if ((this.INI_AmountField.Equals(value) != true)) {
                    this.INI_AmountField = value;
                    this.RaisePropertyChanged("INI_Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBaseRecord {
            get {
                return this.IsBaseRecordField;
            }
            set {
                if ((this.IsBaseRecordField.Equals(value) != true)) {
                    this.IsBaseRecordField = value;
                    this.RaisePropertyChanged("IsBaseRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMultiplier {
            get {
                return this.IsMultiplierField;
            }
            set {
                if ((this.IsMultiplierField.Equals(value) != true)) {
                    this.IsMultiplierField = value;
                    this.RaisePropertyChanged("IsMultiplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OneTime_Amount {
            get {
                return this.OneTime_AmountField;
            }
            set {
                if ((this.OneTime_AmountField.Equals(value) != true)) {
                    this.OneTime_AmountField = value;
                    this.RaisePropertyChanged("OneTime_Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PricingRecordID {
            get {
                return this.PricingRecordIDField;
            }
            set {
                if ((this.PricingRecordIDField.Equals(value) != true)) {
                    this.PricingRecordIDField = value;
                    this.RaisePropertyChanged("PricingRecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesWSTool.ServiceSalesWS.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<SalesWSTool.ServiceSalesWS.Product> ProductReference {
            get {
                return this.ProductReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductReferenceField, value) != true)) {
                    this.ProductReferenceField = value;
                    this.RaisePropertyChanged("ProductReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Reg_Amount {
            get {
                return this.Reg_AmountField;
            }
            set {
                if ((this.Reg_AmountField.Equals(value) != true)) {
                    this.Reg_AmountField = value;
                    this.RaisePropertyChanged("Reg_Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Renewal_Amount {
            get {
                return this.Renewal_AmountField;
            }
            set {
                if ((this.Renewal_AmountField.Equals(value) != true)) {
                    this.Renewal_AmountField = value;
                    this.RaisePropertyChanged("Renewal_Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SpcFlatCostPerSqFt {
            get {
                return this.SpcFlatCostPerSqFtField;
            }
            set {
                if ((this.SpcFlatCostPerSqFtField.Equals(value) != true)) {
                    this.SpcFlatCostPerSqFtField = value;
                    this.RaisePropertyChanged("SpcFlatCostPerSqFt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SpcFlatCostPerSqFtPrice {
            get {
                return this.SpcFlatCostPerSqFtPriceField;
            }
            set {
                if ((this.SpcFlatCostPerSqFtPriceField.Equals(value) != true)) {
                    this.SpcFlatCostPerSqFtPriceField = value;
                    this.RaisePropertyChanged("SpcFlatCostPerSqFtPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SqFtFrom {
            get {
                return this.SqFtFromField;
            }
            set {
                if ((this.SqFtFromField.Equals(value) != true)) {
                    this.SqFtFromField = value;
                    this.RaisePropertyChanged("SqFtFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SqFtTo {
            get {
                return this.SqFtToField;
            }
            set {
                if ((this.SqFtToField.Equals(value) != true)) {
                    this.SqFtToField = value;
                    this.RaisePropertyChanged("SqFtTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/SalesWSServices.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Product : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowGeneralDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowPrepayDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableForCrossSellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CartStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CommissionPctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeOneTimeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOneTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPlanFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ItemTaxOverrideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MissionTemplateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SalesWSTool.ServiceSalesWS.PricingRecord[] PricingRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiresEasyPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchedulingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchedulingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TreeShrubServiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowGeneralDiscount {
            get {
                return this.AllowGeneralDiscountField;
            }
            set {
                if ((this.AllowGeneralDiscountField.Equals(value) != true)) {
                    this.AllowGeneralDiscountField = value;
                    this.RaisePropertyChanged("AllowGeneralDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowPrepayDiscount {
            get {
                return this.AllowPrepayDiscountField;
            }
            set {
                if ((this.AllowPrepayDiscountField.Equals(value) != true)) {
                    this.AllowPrepayDiscountField = value;
                    this.RaisePropertyChanged("AllowPrepayDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AvailableForCrossSell {
            get {
                return this.AvailableForCrossSellField;
            }
            set {
                if ((this.AvailableForCrossSellField.Equals(value) != true)) {
                    this.AvailableForCrossSellField = value;
                    this.RaisePropertyChanged("AvailableForCrossSell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusUnit {
            get {
                return this.BusUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.BusUnitField, value) != true)) {
                    this.BusUnitField = value;
                    this.RaisePropertyChanged("BusUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartState {
            get {
                return this.CartStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CartStateField, value) != true)) {
                    this.CartStateField = value;
                    this.RaisePropertyChanged("CartState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CommissionPct {
            get {
                return this.CommissionPctField;
            }
            set {
                if ((this.CommissionPctField.Equals(value) != true)) {
                    this.CommissionPctField = value;
                    this.RaisePropertyChanged("CommissionPct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastUpdated {
            get {
                return this.DateLastUpdatedField;
            }
            set {
                if ((this.DateLastUpdatedField.Equals(value) != true)) {
                    this.DateLastUpdatedField = value;
                    this.RaisePropertyChanged("DateLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeOneTimeAmount {
            get {
                return this.IncludeOneTimeAmountField;
            }
            set {
                if ((this.IncludeOneTimeAmountField.Equals(value) != true)) {
                    this.IncludeOneTimeAmountField = value;
                    this.RaisePropertyChanged("IncludeOneTimeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOneTime {
            get {
                return this.IsOneTimeField;
            }
            set {
                if ((this.IsOneTimeField.Equals(value) != true)) {
                    this.IsOneTimeField = value;
                    this.RaisePropertyChanged("IsOneTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPlanFlag {
            get {
                return this.IsPlanFlagField;
            }
            set {
                if ((this.IsPlanFlagField.Equals(value) != true)) {
                    this.IsPlanFlagField = value;
                    this.RaisePropertyChanged("IsPlanFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ItemTaxOverride {
            get {
                return this.ItemTaxOverrideField;
            }
            set {
                if ((this.ItemTaxOverrideField.Equals(value) != true)) {
                    this.ItemTaxOverrideField = value;
                    this.RaisePropertyChanged("ItemTaxOverride");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByField, value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MissionTemplateCode {
            get {
                return this.MissionTemplateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MissionTemplateCodeField, value) != true)) {
                    this.MissionTemplateCodeField = value;
                    this.RaisePropertyChanged("MissionTemplateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputType {
            get {
                return this.OutputTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputTypeField, value) != true)) {
                    this.OutputTypeField = value;
                    this.RaisePropertyChanged("OutputType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesWSTool.ServiceSalesWS.PricingRecord[] PricingRecords {
            get {
                return this.PricingRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.PricingRecordsField, value) != true)) {
                    this.PricingRecordsField = value;
                    this.RaisePropertyChanged("PricingRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequiresEasyPay {
            get {
                return this.RequiresEasyPayField;
            }
            set {
                if ((this.RequiresEasyPayField.Equals(value) != true)) {
                    this.RequiresEasyPayField = value;
                    this.RaisePropertyChanged("RequiresEasyPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scheduling {
            get {
                return this.SchedulingField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulingField, value) != true)) {
                    this.SchedulingField = value;
                    this.RaisePropertyChanged("Scheduling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchedulingType {
            get {
                return this.SchedulingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulingTypeField, value) != true)) {
                    this.SchedulingTypeField = value;
                    this.RaisePropertyChanged("SchedulingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceLine {
            get {
                return this.ServiceLineField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceLineField, value) != true)) {
                    this.ServiceLineField = value;
                    this.RaisePropertyChanged("ServiceLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TreeShrubService {
            get {
                return this.TreeShrubServiceField;
            }
            set {
                if ((this.TreeShrubServiceField.Equals(value) != true)) {
                    this.TreeShrubServiceField = value;
                    this.RaisePropertyChanged("TreeShrubService");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesWSResult", Namespace="http://schemas.datacontract.org/2004/07/SalesWSServices.Services")]
    [System.SerializableAttribute()]
    public partial class SalesWSResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounterUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounterUpdated {
            get {
                return this.CounterUpdatedField;
            }
            set {
                if ((this.CounterUpdatedField.Equals(value) != true)) {
                    this.CounterUpdatedField = value;
                    this.RaisePropertyChanged("CounterUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSalesWS.ISalesWS")]
    public interface ISalesWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesWS/GetProducts", ReplyAction="http://tempuri.org/ISalesWS/GetProductsResponse")]
        SalesWSTool.ServiceSalesWS.wsProducts[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesWS/AddPricingRecord", ReplyAction="http://tempuri.org/ISalesWS/AddPricingRecordResponse")]
        SalesWSTool.ServiceSalesWS.SalesWSResult AddPricingRecord(SalesWSTool.ServiceSalesWS.PricingRecord[] newPricingRecords, int productsIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesWS/UpdateBranchProduct", ReplyAction="http://tempuri.org/ISalesWS/UpdateBranchProductResponse")]
        SalesWSTool.ServiceSalesWS.SalesWSResult UpdateBranchProduct(string Branch, int ProductID, int newNumVisits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesWS/GetProductByID", ReplyAction="http://tempuri.org/ISalesWS/GetProductByIDResponse")]
        SalesWSTool.ServiceSalesWS.Product GetProductByID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesWS/DeletePricingByProductID", ReplyAction="http://tempuri.org/ISalesWS/DeletePricingByProductIDResponse")]
        int DeletePricingByProductID(int ProductID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesWSChannel : SalesWSTool.ServiceSalesWS.ISalesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesWSClient : System.ServiceModel.ClientBase<SalesWSTool.ServiceSalesWS.ISalesWS>, SalesWSTool.ServiceSalesWS.ISalesWS {
        
        public SalesWSClient() {
        }
        
        public SalesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SalesWSTool.ServiceSalesWS.wsProducts[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public SalesWSTool.ServiceSalesWS.SalesWSResult AddPricingRecord(SalesWSTool.ServiceSalesWS.PricingRecord[] newPricingRecords, int productsIDs) {
            return base.Channel.AddPricingRecord(newPricingRecords, productsIDs);
        }
        
        public SalesWSTool.ServiceSalesWS.SalesWSResult UpdateBranchProduct(string Branch, int ProductID, int newNumVisits) {
            return base.Channel.UpdateBranchProduct(Branch, ProductID, newNumVisits);
        }
        
        public SalesWSTool.ServiceSalesWS.Product GetProductByID(int ID) {
            return base.Channel.GetProductByID(ID);
        }
        
        public int DeletePricingByProductID(int ProductID) {
            return base.Channel.DeletePricingByProductID(ProductID);
        }
    }
}
